// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "github.com/sjxiang/go-zero-demo/user-api/internal/handler/user"
	"github.com/sjxiang/go-zero-demo/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TestMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/create",
					Handler: user.UserCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/info/:userId",
					Handler: user.UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/update",
					Handler: user.UserUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/test",
				Handler: user.UserTestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
